### ISSUE TITLE
Allow a change to the cluster field 

### ISSUE THREAD

**Issue by maximilianh** [maximilianh/cellBrowser#69] opened 2019-01-31 15:43 UTC
Needed for @slowkow as they have a dataset merge. 

Probably needed for ciona. 

Could be tucked away under View > Cluster Field, shows a dropdown and just does a call.

Otherwise right-click is still there, on fields.

**Comment by PriyankaOyx** [comment] 2022-04-16 13:39
Hi @maximilianh 

Thanks a lot for this amazing tool. I was wondering if there is a way to add pop-up markers for multiple cluster assignments?

For instance, I have clustered the 10x data using both louvain and leiden algorithm (for testing purposes) and have a column assigned to celltypes. I wanted to have an option to click and check markers based on label annotation (which i think is currently applicable to only clusterField). I tried making changes to the config file to provide multiple clusterFields but that just created more problems.

Any solution for the same?
Any guidance would be highly appreciated.

**Comment by maximilianh** [comment] 2022-04-19 08:25
Yes! Have a look at cells-test.gi.ucsc.edu. It's on the left side menu, just select a different "Cluster Field" @mxposed added the code a while ago. Let us know if you have any feedback on it. It's not released yet, but coming very soon to the public site, I need to remove numeric fields from it and make sure that after a change of the layout the label fields are redrawn.

**Comment by PriyankaOyx** [comment] 2022-04-26 06:02
Thanks a ton, that's a great help. Hope to see the update in the development version too.

But for now the issue is resolved.

**Comment by matthewspeir** [comment] 2022-05-24 18:08
I think we can close this now that the 'label by annotation' feature is available.

**Closed by matthewspeir** 2022-05-24 18:08 UTC
