### ISSUE TITLE
cbScanpy failing with error: "ValueError: cannot reindex with a non-unique indexer"

### ISSUE THREAD

**Issue by matthewspeir** [maximilianh/cellBrowser#66] opened 2019-01-29 22:31 UTC
Command, cbScanpy output and error at the bottom:
```
$ cbScanpy -e ica_cord_blood_h5.h5 -o cbScanpyOut -n ICA_Cord_Blood
INFO:root:Creating cbScanpyOut
cbScanpy $Id$
Input file: ica_cord_blood_h5.h5
Start time: 2019-01-29 12:45:38.211369
scanpy==1.3.7 anndata==0.6.18 numpy==1.16.0 scipy==1.2.0 pandas==0.24.0 scikit-learn==0.20.2 statsmodels==0.9.0 
INFO:root:Loading expression matrix: 10X h5 format
Variable names are not unique. To make them unique, call `.var_names_make_unique`.
INFO:root:Writing scanpy matrix to cbScanpyOut/exprMatrix.tsv.gz
INFO:root:Transposing matrix
INFO:root:Converting csc matrix to row-sparse matrix
INFO:root:Writing gene-by-gene, without using pandas
INFO:root:Writing 33694 genes in total
INFO:root:Wrote 0 genes
INFO:root:Wrote 2000 genes
INFO:root:Wrote 4000 genes
INFO:root:Wrote 6000 genes
INFO:root:Wrote 8000 genes
INFO:root:Wrote 10000 genes
INFO:root:Wrote 12000 genes
INFO:root:Wrote 14000 genes
INFO:root:Wrote 16000 genes
INFO:root:Wrote 18000 genes
INFO:root:Wrote 20000 genes
INFO:root:Wrote 22000 genes
INFO:root:Wrote 24000 genes
INFO:root:Wrote 26000 genes
INFO:root:Wrote 28000 genes
INFO:root:Wrote 30000 genes
INFO:root:Wrote 32000 genes
Data has 384000 samples/observations
Data has 33694 genes/variables
Basic filtering: keep only cells with min 200 genes
Variable names are not unique. To make them unique, call `.var_names_make_unique`.
Variable names are not unique. To make them unique, call `.var_names_make_unique`.
Basic filtering: keep only gene with min 3 cells
Variable names are not unique. To make them unique, call `.var_names_make_unique`.
Variable names are not unique. To make them unique, call `.var_names_make_unique`.
After filtering: Data has 320644 samples/observations and 24248 genes/variables
INFO:root:'geneIdType' is not specified in config file.
INFO:root:Auto-detected gene IDs type: symbols
Remove cells with more than 0.050000 percent of mitochondrial genes
Computing percentage of mitochondrial genes
Remove cells with less than 10 and more than 15000 genes
Filtering cells
After filtering: Data has 273034 samples/observations and 24248 genes/variables
Expression normalization, counts per cell = 10000
Variable names are not unique. To make them unique, call `.var_names_make_unique`.
Variable names are not unique. To make them unique, call `.var_names_make_unique`.
Variable names are not unique. To make them unique, call `.var_names_make_unique`.
Variable names are not unique. To make them unique, call `.var_names_make_unique`.
Finding highly variable genes: min_mean=0.012500, max_mean=3.000000, min_disp=0.500000
Traceback (most recent call last):
  File "/cluster/home/mspeir/ENV_cellbrowser/bin/cbScanpy", line 11, in <module>
    sys.exit(cbScanpyCli())
  File "/cluster/home/mspeir/ENV_cellbrowser/lib/python3.6/site-packages/cellbrowser/cellbrowser.py", line 3630, in cbScanpyCli
    adata = cbScanpy(matrixFname, confFname, figDir, logFname, matrixOutFname)
  File "/cluster/home/mspeir/ENV_cellbrowser/lib/python3.6/site-packages/cellbrowser/cellbrowser.py", line 3443, in cbScanpy
    filter_result = sc.pp.filter_genes_dispersion(adata.X, min_mean=minMean, max_mean=maxMean, min_disp=minDisp)
  File "/cluster/home/mspeir/ENV_cellbrowser/lib/python3.6/site-packages/scanpy/preprocessing/_deprecated/highly_variable_genes.py", line 131, in filter_genes_dispersion
    gen_indices = np.where(one_gene_per_bin[df['mean_bin']])[0].tolist()
  File "/cluster/home/mspeir/ENV_cellbrowser/lib/python3.6/site-packages/pandas/core/series.py", line 911, in __getitem__
    return self._get_with(key)
  File "/cluster/home/mspeir/ENV_cellbrowser/lib/python3.6/site-packages/pandas/core/series.py", line 953, in _get_with
    return self.reindex(key)
  File "/cluster/home/mspeir/ENV_cellbrowser/lib/python3.6/site-packages/pandas/core/series.py", line 3734, in reindex
    return super(Series, self).reindex(index=index, **kwargs)
  File "/cluster/home/mspeir/ENV_cellbrowser/lib/python3.6/site-packages/pandas/core/generic.py", line 4346, in reindex
    fill_value, copy).__finalize__(self)
  File "/cluster/home/mspeir/ENV_cellbrowser/lib/python3.6/site-packages/pandas/core/generic.py", line 4359, in _reindex_axes
    tolerance=tolerance, method=method)
  File "/cluster/home/mspeir/ENV_cellbrowser/lib/python3.6/site-packages/pandas/core/indexes/category.py", line 503, in reindex
    raise ValueError("cannot reindex with a non-unique indexer")
ValueError: cannot reindex with a non-unique indexer
```

This is using the 'Raw Counts Matrix - Cord Blood' h5 file is from 'Census of Immune Cells' data set here: https://preview.data.humancellatlas.org/.

**Comment by maximilianh** [comment] 2019-01-30 14:03
Oh darn, I spent quite a while trying to track this down, then had lunch
and only then had the idea of googling it. It's a known problem of your
version combination.

https://github.com/theislab/scanpy/issues/450

It's working on my machine and I just saw that my version of pandas is
pandas==0.22.0.

This problem has just been fixed in Scanpy. So there are at least two
options for you:

- you can downgrade pandas with pip install pandas==0.23.0
- you can upgrade scanpy to the current master branch (git clone + python
setup.py)

**Comment by maximilianh** [comment] 2019-01-30 17:38
Closing this as it's another scanpy problem.

**Closed by maximilianh** 2019-01-30 17:38 UTC

**Comment by cotedivoir** [comment] 2020-01-29 00:45
got the same issue, tried to downgrade pandas as you suggested, still there:

`cbScanpy -e filtered_gene_bc_matrices/hg19/matrix.mtx -o scanpyOut -n pbmc3k
INFO:root:Loading Scanpy libraries
INFO:numexpr.utils:NumExpr defaulting to 8 threads.
INFO:get_version:dirname: Trying to get version of get_version from dirname /home/cotedivoir/.local/lib/python3.6/site-packages
INFO:get_version:dirname: Failed; Does not match re.compile('get[_-]version-([\\d.]+?)(?:\\.dev(\\d+))?(?:[_+-]([0-9a-zA-Z.]+))?$')
INFO:get_version:git: Trying to get version from git in directory /home/cotedivoir/.local/lib/python3.6/site-packages
INFO:get_version:git: Failed; The top-level directory of the current Git repository is not the same as the root directory of the distribution
INFO:get_version:metadata: Trying to get version for get_version in dir /home/cotedivoir/.local/lib/python3.6/site-packages
INFO:get_version:metadata: Succeeded
INFO:get_version:dirname: Trying to get version of legacy_api_wrap from dirname /home/cotedivoir/.local/lib/python3.6/site-packages
INFO:get_version:dirname: Failed; Does not match re.compile('legacy[_-]api[_-]wrap-([\\d.]+?)(?:\\.dev(\\d+))?(?:[_+-]([0-9a-zA-Z.]+))?$')
INFO:get_version:git: Trying to get version from git in directory /home/cotedivoir/.local/lib/python3.6/site-packages
INFO:get_version:git: Failed; The top-level directory of the current Git repository is not the same as the root directory of the distribution
INFO:get_version:metadata: Trying to get version for legacy_api_wrap in dir /home/cotedivoir/.local/lib/python3.6/site-packages
INFO:get_version:metadata: Succeeded
INFO:root:cbScanpy $Id$
INFO:root:Input file: filtered_gene_bc_matrices/hg19/matrix.mtx
INFO:root:Restricting OPENBLAS to 4 threads
INFO:root:Start time: 2020-01-28 16:40:36.219846
scanpy==1.4.5.post2 anndata==0.7.1 umap==0.3.10 numpy==1.18.1 scipy==1.4.1 pandas==0.22.0 scikit-learn==0.22.1 statsmodels==0.11.0
INFO:root:Loading expression matrix: mtx format
INFO:root:Data has 2700 samples/observations
INFO:root:Data has 32738 genes/variables
INFO:root:Basic filtering: keep only cells with min 200 genes
Variable names are not unique. To make them unique, call `.var_names_make_unique`.
Variable names are not unique. To make them unique, call `.var_names_make_unique`.
INFO:root:Basic filtering: keep only gene with min 3 cells
Variable names are not unique. To make them unique, call `.var_names_make_unique`.
Variable names are not unique. To make them unique, call `.var_names_make_unique`.
INFO:root:After filtering: Data has 2700 samples/observations and 13714 genes/variables
INFO:root:'geneIdType' is not specified in config file or set to 'auto'.
INFO:root:Auto-detected gene IDs type: symbols
INFO:root:Remove cells with more than 0.050000 percent of mitochondrial genes
INFO:root:Computing percentage of mitochondrial genes
Traceback (most recent call last):
  File "/home/cotedivoir/.local/bin/cbScanpy", line 11, in <module>
    sys.exit(cbScanpyCli())
  File "/home/cotedivoir/.local/lib/python3.6/site-packages/cellbrowser/cellbrowser.py", line 5390, in cbScanpyCli
    adata, params = cbScanpy(matrixFname, metaFname, inCluster, confFname, figDir, logFname)
  File "/home/cotedivoir/.local/lib/python3.6/site-packages/cellbrowser/cellbrowser.py", line 5040, in cbScanpy
    adata.obs['percent_mito'] = np.sum(adata[:, mito_genes].X, axis=1) / np.sum(adata.X, axis=1)
  File "/home/cotedivoir/.local/lib/python3.6/site-packages/anndata/_core/anndata.py", line 1049, in __getitem__
    oidx, vidx = self._normalize_indices(index)
  File "/home/cotedivoir/.local/lib/python3.6/site-packages/anndata/_core/anndata.py", line 1030, in _normalize_indices
    return _normalize_indices(index, self.obs_names, self.var_names)
  File "/home/cotedivoir/.local/lib/python3.6/site-packages/anndata/_core/index.py", line 34, in _normalize_indices
    ax1 = _normalize_index(ax1, names1)
  File "/home/cotedivoir/.local/lib/python3.6/site-packages/anndata/_core/index.py", line 89, in _normalize_index
    positions = index.get_indexer(indexer)
  File "/home/cotedivoir/.local/lib/python3.6/site-packages/pandas/core/indexes/base.py", line 2687, in get_indexer
    raise InvalidIndexError('Reindexing only valid with uniquely'
pandas.core.indexes.base.InvalidIndexError: Reindexing only valid with uniquely valued Index objects`

**Comment by maximilianh** [comment] 2020-01-29 15:14
It looks like this is scanpy==1.4.5.post2 anndata==0.7.1 umap==0.3.10
numpy==1.18.1 scipy==1.4.1 pandas==0.22.0 scikit-learn==0.22.1
statsmodels==0.11.0

How did you install sacnpy?

>

**Comment by maximilianh** [comment] 2020-01-29 15:14
overall, it doesn't look like this is an issue with the cellbrowser,
but rather with your scanpy installation?

how did you install the cellbrowser and which version?

**Comment by cotedivoir** [comment] 2020-01-29 17:11
Thank you for the reply!

version: cellbrowser (0.7.7)
how installed: pip3 install

**Comment by maximilianh** [comment] 2020-01-29 20:57
Thanks! How did you install scanpy? With conda?

**Comment by cotedivoir** [comment] 2020-01-29 23:36
no, same way - pip3

**Comment by maximilianh** [comment] 2020-01-30 14:22
Hm, I can't reproduce this... is this on OSX or Linux? If yes, which linux
version?

This doesn't seem to be a cellbrowser problem, but something with your
scanpy install... did you ask the scanpy people?

**Comment by cotedivoir** [comment] 2020-01-31 22:37
think i should have started with this: i use WSL for windows with Ubuntu distribution

**Comment by maximilianh** [comment] 2020-02-01 22:47
Urgs. OK, I don't really want to dig into this. It's a problem with scanpy,
partially due to them constantly making breaking changes. Can you ask them?
I don't know about about scanpy. You can probably easily reproduce this
problem by running a standard scanpy tutorial.

Can I ask why you're using the scanpy pipeline of cellbrowser? Do you have
your own results or is this part of a term project and cbScanpy has a
ready-made pipeline for single cell analysis?

**Comment by cotedivoir** [comment] 2020-02-02 01:28
ok, sorry for bothering, i'm just trying to learn more about single cell data analysis. not much structured information around. so i found cellbrowser, and as you say cbScanpy has already prebuild pipeline so i decided that would be a way to start

**Comment by maximilianh** [comment] 2020-02-02 19:23
It usually is but only if your scanpy works. The recommended way to install
scanpy is conda, it has a ton of dependencies.

**Comment by maximilianh** [comment] 2020-02-02 19:24
Oh that would be the reason by the way: install scanpy with conda! I don’t
think the pip way is recommended anymore. Try conda as let me know if it
works then.

**Comment by cotedivoir** [comment] 2020-02-07 21:46
Hi! Installed scanpy via conda, still get the same error

**Comment by matthewspeir** [comment] 2020-02-13 17:34
@ivirshup We think this might be an issue with scanpy (or maybe just their install of scanpy). Do you have insights into the issues this user is seeing?
